### ISSUE TITLE
Arduino-Side Protocol

### ISSUE THREAD

**Issue by csmith1188** [Logan24057/IRL-Tech#11]
In an Arduino sketch, it must be able to handle the following commands over Serial:

- w0/<string>
- w1/<string>
- w2/<string>
- w3/<string>

(will write the string to the record at that index)

- r0/<string>
- r1/<string>
- r2/<string>
- r3/<string>

(will read record at that index)

**Comment by Logan24057** [comment]
No way to write to specific records using the arduino libraries in Arduino IDE as far as I know. So I will have to send the NDEF records to Node.JS and have it change the selected record there, and then send it back to arduino to rewrite all the records including the changed one.

**Comment by Logan24057** [comment]
It is now able to read specific records, but it still cannot write to specific records.
